import os
import json
import tempfile
import shutil
from pathlib import Path
from rich.console import Console
from .core import generate_content
from .utils import run_shell, check_gh_auth, get_user_email

console = Console()

def fetch_repos(username):
    """
    Fetches public repositories for the user.
    """
    console.print("[cyan]Fetching repositories...[/cyan]")
    cmd = 'gh repo list --visibility=public --limit 100 --json name,description,url,isPrivate,isArchived,stargazerCount'
    try:
        output = run_shell(cmd)
        return json.loads(output)
    except Exception as e:
        console.print(f"[red]Failed to fetch repos:[/red] {e}")
        return []

def filter_repos(repos, username, strategy="FULL_GEN", existing_content=""):
    """
    Filters out junk, private, archived, and already-included repos.
    """
    candidates = []
    
    junk_names = ["test", "export", "WPy64", "PROFILE_DRAFT.md", "temp"]
    
    for r in repos:
        name = r['name']
        
        # Basic filters
        if name == username: continue
        if r.get('isPrivate'): continue
        if r.get('isArchived'): continue
        if name in junk_names: continue
        if name.endswith(".exe"): continue
        
        # Strategy filter
        if strategy == "SMART_UPDATE":
            # Simple check if repo name exists in current profile content
            if name in existing_content:
                continue
        
        candidates.append(r)
        
    return candidates

def generate_profile(username, force=False, mode="fast"):
    """
    Main function to generate or update the profile.
    """
    if not username:
        username = check_gh_auth()
        if not username:
            console.print("[red]Not logged into GitHub CLI. Run 'gh auth login' first.[/red]")
            return

    console.print(f"[green]Authenticated as: {username}[/green]")
    
    # Discovery
    current_content = ""
    strategy = "FULL_GEN"
    
    if not force:
        try:
            console.print("[cyan]Checking for existing profile...[/cyan]")
            current_content = run_shell(f'gh api "repos/{username}/{username}/readme" --headers "Accept: application/vnd.github.raw"', check=False)
            if current_content and len(current_content) > 200:
                console.print("[green]Found existing robust profile. Switching to SMART_UPDATE.[/green]")
                strategy = "SMART_UPDATE"
            else:
                 console.print("[yellow]Profile basic or missing. Using FULL_GEN.[/yellow]")
        except:
            pass

    # Fetch & Filter
    repos = fetch_repos(username)
    candidates = filter_repos(repos, username, strategy, current_content)
    
    if not candidates:
        console.print("[green]No new repositories to add.[/green]")
        return

    # Prompt Engineering
    candidates_str = "\n".join([f"- Name: {r['name']}\n  Desc: {r['description'] or ''}\n  URL: {r['url']}" for r in candidates])
    
    prompt = ""
    if strategy == "SMART_UPDATE":
        prompt = f"""
Task: Update a GitHub Profile README.
Existing Markdown:
'''
{current_content}
'''

New Projects to Add:
{candidates_str}

Instructions:
1. Integrate the 'New Projects' into the 'Existing Markdown' naturally.
2. Place them under appropriate categories.
3. MATCH THE STYLE: If badges or tables are used, mimic them.
4. STRICTLY NO EMOJIS in output.
5. Output the FULL updated Markdown content.
"""
    else:
        # Full Gen
        skeleton = f"# Hi, I am {username}\n\nI build tools and software.\n\n## Projects\n\n{{DYNAMIC_PROJECTS}}\n\n---\n*Generated by Git-Alchemist*"
        prompt = f"""
Task: Generate a Project Showcase for a GitHub Profile.
Target Skeleton:
'''
{skeleton}
'''

Projects List:
{candidates_str}

Instructions:
1. Group projects into 3-6 meaningful categories.
2. List format: '- **[Name](URL)** - Description'.
3. Replace '{{DYNAMIC_PROJECTS}}' with the list.
4. STRICTLY NO EMOJIS.
5. Output the FULL final Markdown.
"""

    console.print(f"[magenta]Generating content with Gemini ({mode} mode)...[/magenta]")
    result = generate_content(prompt, mode=mode)
    
    if not result:
        return

    # Post-processing
    final_md = result.replace("```markdown", "").replace("```", "").strip()
    if "*Generated by Git-Alchemist*" not in final_md:
        final_md += "\n\n---\n*Generated by Git-Alchemist*"

    # Save Draft
    with open("PROFILE_DRAFT.md", "w", encoding="utf-8") as f:
        f.write(final_md)
    console.print(f"[magenta]Draft saved to PROFILE_DRAFT.md[/magenta]")
    
    # PR Workflow
    create_pr = console.input("[cyan]Do you want to open a PR to update your profile? (y/n): [/cyan]")
    if create_pr.lower() == 'y':
        deploy_profile(username, final_md)

def deploy_profile(username, content):
    """
    Clones the profile repo, updates README, and opens a PR.
    """
    temp_dir = tempfile.mkdtemp(prefix="git_alchemist_")
    try:
        console.print("[cyan]Cloning profile repository...[/cyan]")
        run_shell(f'gh repo clone {username}/{username} {temp_dir}')
        
        repo_dir = Path(temp_dir) / username  # gh repo clone creates a subdir
        if not repo_dir.exists():
            repo_dir = Path(temp_dir) # Sometimes it doesn't? 
            
        # Write file
        readme_path = repo_dir / "README.md"
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        # Git ops
        cwd = os.getcwd()
        os.chdir(repo_dir)
        
        branch_name = "profile-update-git-alchemist"
        run_shell(f'git checkout -b {branch_name}')
        
        user_email = get_user_email() or f"{username}@users.noreply.github.com"
        run_shell(f'git config user.name "{username}"')
        run_shell(f'git config user.email "{user_email}"')
        
        run_shell('git add README.md')
        run_shell('git commit -m "Update profile via Git-Alchemist"')
        run_shell(f'git push -u origin {branch_name} --force') # Force just in case branch exists
        
        console.print("[green]Opening PR...[/green]")
        run_shell('gh pr create --title "Git-Alchemist Profile Update" --body "Automated update." --web')
        
        os.chdir(cwd)
        
    except Exception as e:
        console.print(f"[red]Deployment failed:[/red] {e}")
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)
